flags: {}
nix:
  packages:
  - cabal-install
  - libarchive
  - zlib
  enable: true
extra-deps:
- attoparsec-0.13.0.2
- bytestring-builder-0.10.8.1.0
- hashable-1.2.4.0
- io-streams-1.3.5.0
- network-2.6.3.1
- primitive-0.6.1.0
- scientific-0.3.4.9
- text-1.2.2.1
- vector-0.11.0.0
- zlib-0.6.1.1
- zlib-bindings-0.1.1.5
resolver: ghc-8.0.1
